Error handling functionality
dfds/selfservice-portal pull request #12
Opened 2023-07-06 11:48 UTC by HrisyToteva

closes dfds/cloudplatform/issues/1704

2023-07-06 14:15 UTC, SEQUOIIA commented
🫡

2023-07-06 14:38 UTC, kralle333 commented on fake_dependencies/selfservice-api/src/routes/capabilities.ts
> +
Can you add a boolean toggle like you did in kafkatopics.ts to make it easier to test error handling functionality?

2023-07-06 14:41 UTC, kralle333 commented on src/src/hooks/Topics.js
> +
is this some comments you forgot to delete?

2023-07-06 15:02 UTC, SEQUOIIA commented
I'll take a look later ☺️

2023-07-06 20:36 UTC, SEQUOIIA requested changes
Phew, reviewing this PR is like eating a 16 course meal, sheeesh. Sometimes it's not possible to do smaller PRs or split them up in chunks, but I do think it would've benefitted this one. Slightly concerned that I might've missed something given how big it is 😅.

I've included a lot of mentions of removing `console.log`, primarily if they are not triggered by an error. If you think you'd need them again for debugging purposes, maybe we should implement a way of toggling those particular `console.log` statements so if you're running the app in development mode, they are triggered, and if the app is running in production mode, they don't trigger.

If you disagree with any of statements above or the individual comments in the files, or want to understand why, ask away. Just because I want something changed doesn't mean I'm right. Perhaps there's a perspective that I'm missing.

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/AppContext.js
> +    // await selfServiceApiClient.createCapability({name, description});
Remove line 48. Unnecessary.

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/ErrorContext.js
> +    // if (err== 401){
Remove all commented out code, unless you can justify why it should be there

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/ErrorContext.js
> +  // useEffect(() => {
Remove all commented out code, unless you can justify why it should be there

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/ErrorDisplay.js
> +      {/* {(error.map(e => <Toast intent="critical">
Remove all commented out code, unless you can justify why it should be there

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/SelfServiceApiClient.js
> +    // async getCapabilities(){
Remove all commented out code, unless you can justify why it should be there

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/SelfServiceApiClient.js
> +    // async createCapability(capabilityDefinition){
Remove all commented out code, unless you can justify why it should be there

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/SelfServiceApiClient.js
> +    // async getCapabilityMembers(capabilityDefinition) {
Remove all commented out code, unless you can justify why it should be there

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/SelfServiceApiClient.js
> +function composeUrl(...args) {
Duplicate composeUrl function in src/src/Utils.js as far as I can see

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/Utils.js
> +export function composeUrl(...args) {
Duplicate composeUrl function in src/src/SelfServiceApiClient.js as far as I can see

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/Utils.js
> +export function composeUrl2(segments) {
Instead of composeUrl and composeUrl2, give them a suffix that tells what they do differently, so they are easier to differentiate

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/components/Toast/index.js
> +            {/* <Button size="small" variation="outlined">Details</Button> */}
Remove all commented out code, unless you can justify why it should be there

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/components/Toast/toast.module.css
> +    /* top: 20px;
Remove all commented out code, unless you can justify why it should be there

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/hooks/SelfServiceApi.js
> +        console.log("segmets: ", urlSegments);
Remove line 25. Unnecessary logging in happy path.

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/hooks/SelfServiceApi.js
> +                // if (httpResponse.headers.get("Content-Type") === "application/problem+json") {
Remove all commented out code, unless you can justify why it should be there

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/hooks/Topics.js
> +        // const url =  composeUrl("kafkatopics");
Remove all commented out code, unless you can justify why it should be there

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/pages/capabilities/SelectedCapabilityContext.js
> +        // if (members){
Remove all commented out code, unless you can justify why it should be there

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/pages/capabilities/SelectedCapabilityContext.js
>        console.log('requesting access to cluster', cluster);
Remove line 209 & 215. Unnecessary logging in happy path.

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/pages/capabilities/SelectedCapabilityContext.js
>          // await loadMembershipApplications();
Remove all commented out code, unless you can justify why it should be there

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/pages/capabilities/SelectedCapabilityContext.js
> +            console.log(membersList);
Remove line 293. Unnecessary logging in happy path.

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/pages/topics/index.js
> +            console.log(topicsList)
Remove line 98. Unnecessary logging in happy path.

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/pages/topics/index.js
> +        // const fetchTopics = async (c) => {
Remove all commented out code, unless you can justify why it should be there

2023-07-06 20:36 UTC, SEQUOIIA commented on src/src/pages/topics/index.js
> +        // fetchKafkaclusters().then((c) => fetchTopics(c));
Remove all commented out code, unless you can justify why it should be there

2023-07-11 09:23 UTC, SEQUOIIA approved these changes
Let's try and see what happens 😂

2023-07-11 09:32 UTC, kralle333 approved these changes
Looks good. Make sure the test is green before merging ;)

2023-07-11 13:25 UTC, merged