cannot evolve message contarcts that are not Provisioned
dfds/selfservice-portal pull request #236
Opened 2024-01-30 14:02 UTC by HrisyToteva

closes dfds/cloudplatform/issues/2553

# Additional Review Notes

the frontend doesn’t allow you to evolve Messages Contracts that are not provisioned

<img width="1062" alt="image" src="https://github.com/dfds/selfservice-portal/assets/58768740/687bbd05-d1f8-40ba-8e8e-499f8961514b">

2024-01-30 15:14 UTC, kralle333 requested changes
Great job! That was really quick. I have some smaller comments and then its ready to get in

2024-01-30 15:14 UTC, kralle333 commented on src/src/pages/capabilities/KafkaCluster/MessageContract.module.css
> +  /* opacity: 0.25; */
remove this :)

2024-01-30 15:14 UTC, kralle333 commented on src/src/pages/capabilities/KafkaCluster/MessageContracts.js
> +                  {`Version${contract.schemaVersion}${
you are missing a space between Version and the number

2024-01-30 15:14 UTC, kralle333 commented on src/src/pages/capabilities/KafkaCluster/MessageContracts.js
> +                    contract.status !== "Provisioned"
inside of MessageContracts.js we have an enum for the statuses. Use that instead
<img width="342" alt="image" src="https://github.com/dfds/selfservice-portal/assets/5738476/d5803097-e8ef-4a59-a551-072b02ba92ff">

2024-01-30 15:14 UTC, kralle333 commented on src/src/pages/capabilities/KafkaCluster/MessageContracts.js
> +                  selectedContract.status !== "Provisioned" ? true : false
same here, use the enum

2024-01-30 15:14 UTC, kralle333 commented on src/src/pages/capabilities/KafkaCluster/MessageContracts.js
> +                selectedContract.status !== "Provisioned"
and here

2024-01-31 08:29 UTC, HrisyToteva commented on src/src/pages/capabilities/KafkaCluster/MessageContracts.js
> +                  selectedContract.status !== "Provisioned" ? true : false
good point!

2024-01-31 09:23 UTC, kralle333 approved these changes
Thank you!

2024-01-31 09:31 UTC, merged