fixed error with the react table keys and the one with the empty header
dfds/selfservice-portal pull request #74
Opened 2023-09-15 12:25 UTC by HrisyToteva

fixed error:
![image](https://github.com/dfds/selfservice-portal/assets/58768740/32162555-4c2b-4553-845d-14039a401bcb)

# Additional Review Notes
Put your complementary notes here for helping reviewers review your changes.

2023-09-15 12:56 UTC, kralle333 requested changes

2023-09-15 12:56 UTC, kralle333 commented on src/src/pages/capabilities/MyCapabilities.js
> +        header: 'dddd',
dddd?

2023-09-15 12:56 UTC, kralle333 commented on src/src/pages/capabilities/MyCapabilities.js
> +import {Tooltip} from '@mui/material';
are you using this import?

2023-09-19 09:12 UTC, SEQUOIIA commented on src/src/pages/capabilities/MyCapabilities.js
> +        header: 'dddd',
Addressed in new commit

2023-09-19 09:13 UTC, SEQUOIIA commented on src/src/pages/capabilities/MyCapabilities.js
> +import {Tooltip} from '@mui/material';
Addressed in new commit

2023-09-20 07:46 UTC, kralle333 approved these changes
looks nice!

2023-09-20 09:23 UTC, merged